on:
  push:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      VAR1: "earth"
    steps:
      - name: access VAR1
        run: echo "Value is $VAR1"
      - name: print github context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"
